name: Build and Upload SDK

on:
  push:
    branches:
      - humble
  schedule:
    # Every Monday at 06:00 UTC.
    - cron: "0 6 * * 1"
  workflow_dispatch:

  build-and-upload:
    uses: canonical/sdkcraft-actions/.github/workflows/upload.yml@main
    with:
      platforms: '["amd64","arm64"]'
      ref: ${{ github.ref_name }}
      track: ${{ github.ref_name }}
      risk: stable
    secrets:
      SDKCRAFT_STORE_CREDENTIALS: ${{ secrets.SDKCRAFT_STORE_CREDENTIALS_PROD }}
